import type { Metadata } from "next";
import ContactPop from "./_components/ContactPop";
// import ContactPop from "./components/ContactPop";
import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Still Motion Pictures",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="mx-auto">
            <Navbar />
            {children}
            {/* <ContactPop /> */}
            <Footer />
        </main>
      </body>
    </html>
  );
}
// max-w-6xl